# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3152521adeb13f70d7d4e8882f9ac81a4a0fb72b881960f7f9fc583b0713a549541fc6b0bd4604ca4c6d86e10eef0061efd093fe358c535d2afe4485c93f360

test:
  secret_key_base: d6c211f731c5bd87e975e6ea7ab51923171ec0abc76a70ae153fd7b1b5172d20e4184e09d13b40dd5512f5a26335d03ae764258a950ebfdf69a0afdbad840130

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
